import { BiLogoPostgresql } from 'react-icons/bi'
import { BsFillBootstrapFill } from 'react-icons/bs'
import {
  SiAstro,
  SiAmazonaws,
  SiChakraui,
  SiCss3,
  SiDjango,
  SiExpo,
  SiExpress,
  SiFirebase,
  SiFramer,
  SiGithub,
  SiGit,
  SiGooglecloud,
  SiGraphql,
  SiGulp,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiJira,
  SiJson,
  SiJsonwebtokens,
  SiMui,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiNuxtdotjs,
  SiAuth0,
  SiPhp,
  SiPrisma,
  SiPuppeteer,
  SiPython,
  SiRabbitmq,
  SiReact,
  SiReacthookform,
  SiReactquery,
  SiReactrouter,
  SiReacttable,
  SiRedis,
  SiRedux,
  SiSass,
  SiStorybook,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiVuedotjs
} from 'react-icons/si'
import { TbApi, TbBrandThreejs } from 'react-icons/tb'
import { FaGitlab } from 'react-icons/fa'
import { BsKanban } from 'react-icons/bs'

type stacksProps = {
  [key: string]: JSX.Element
}

const iconSize = '100%'

export const STACKS: stacksProps = {
  PHP: <SiPhp size={iconSize} className="text-blue-500" />,
  JavaScript: <SiJavascript size={iconSize} className="text-yellow-400" />,
  TypeScript: <SiTypescript size={iconSize} className="text-blue-400" />,
  'Next.js': <SiNextdotjs size={iconSize} />,
  'React.js': <SiReact size={iconSize} className="text-sky-500" />,
  TailwindCSS: <SiTailwindcss size={iconSize} className="text-cyan-300" />,
  Bootstrap: <BsFillBootstrapFill size={iconSize} className="text-purple-500" />,
  GraphQL: <SiGraphql size={iconSize} className="text-pink-600" />,
  'Material UI': <SiMui size={iconSize} className="text-sky-400" />,
  Vite: <SiVite size={iconSize} className="text-purple-500" />,
  PostgreSQL: <BiLogoPostgresql size={iconSize} className="text-blue-400" />,
  ChakraUI: <SiChakraui size={iconSize} className="text-teal-500" />,
  'React Native': <SiReact size={iconSize} className="text-sky-600" />,
  Expo: <SiExpo size={iconSize} />,
  SASS: <SiSass size={iconSize} className="text-pink-600" />,
  Gulp: <SiGulp size={iconSize} className="text-red-500" />,
  Firebase: <SiFirebase size={iconSize} className="text-yellow-500" />,
  'Framer Motion': <SiFramer size={iconSize} />,
  'Nuxt.js': <SiNuxtdotjs size={iconSize} className="text-green-600" />,
  'Vue.js': <SiVuedotjs size={iconSize} className="text-green-500" />,
  Jest: <SiJest size={iconSize} className="text-orange-600" />,
  'Express.js': <SiExpress size={iconSize} />,
  Redux: <SiRedux size={iconSize} className="text-purple-500" />,
  'React Query': <SiReactquery size={iconSize} className="text-red-600" />,
  HTML5: <SiHtml5 size={iconSize} className="text-orange-500" />,
  CSS3: <SiCss3 size={iconSize} className="text-blue-500" />,
  Prisma: <SiPrisma size={iconSize} className="text-teal-500" />,
  'Node.js': <SiNodedotjs size={iconSize} className="text-green-600" />,
  GitHub: <SiGithub size={iconSize} />,
  Storybook: <SiStorybook size={iconSize} className="text-pink-500" />,
  'React Router': <SiReactrouter size={iconSize} className="text-pink-500" />,
  'React Hook Form': <SiReacthookform size={iconSize} className="text-pink-500" />,
  'React Table': <SiReacttable size={iconSize} className="text-rose-600" />,
  Astro: <SiAstro size={iconSize} className="text-purple-500" />,
  Json: <SiJson size={iconSize} className="text-neutral-700" />,
  
  // New additions
  'Three.js': <TbBrandThreejs size={iconSize} className="text-black" />,
  Python: <SiPython size={iconSize} className="text-blue-500" />,
  Django: <SiDjango size={iconSize} className="text-green-700" />,
  REST: <TbApi size={iconSize} className="text-orange-500" />,
  JWT: <SiJsonwebtokens size={iconSize} className="text-purple-500" />,
  OAuth: <SiAuth0 size={iconSize} className="text-gray-600" />,
  RabbitMQ: <SiRabbitmq size={iconSize} className="text-orange-500" />,
  MySQL: <SiMysql size={iconSize} className="text-blue-500" />,
  MongoDB: <SiMongodb size={iconSize} className="text-green-500" />,
  Redis: <SiRedis size={iconSize} className="text-red-500" />,
  AWS: <SiAmazonaws size={iconSize} className="text-orange-400" />,
  'Google Cloud': <SiGooglecloud size={iconSize} className="text-blue-400" />,
  Puppeteer: <SiPuppeteer size={iconSize} className="text-green-400" />,
  'CI/CD': <FaGitlab size={iconSize} className="text-orange-500" />,
  Git: <SiGit size={iconSize} className="text-orange-600" />,
  Agile: <BsKanban size={iconSize} className="text-blue-500" />,
  Scrum: <BsKanban size={iconSize} className="text-green-500" />,
  Jira: <SiJira size={iconSize} className="text-blue-500" />
}
