name: Running auto label on PR

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: Auto Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          config-path: .github/labeler.yml
